export * from './Cadastro'
export * from './Inicial'
export * from './Perfil'
export * from './Regras'
export * from './ResultadosPerfil'
export * from './Suporte'
export * from './TelaInvestimentosNumero'
export * from './Urubuzado'
